In [1]:
import pandas as pd
import support.df_init as init

df = init.init()
df

,originalTitle,rating,startYear,endYear,runtimeMinutes,awardWins,numVotes,worstRating,bestRating,totalImages,...,castNumber,companiesNumber,averageRating,regions,externalLinks,writerCredits,directorsCredits,soundMixes,quotesTotal,totalMedia
0,Carmencita,"(5, 6]",1894,1894.0,1.0,0,2089,1,10,2,...,1,3,5.7,"[DE, US, HU, GR, RU, UA, JP]",9,0,1,[silent],0,6
1,Un bon bock,"(5, 6]",1892,1892.0,12.0,0,183,1,10,2,...,0,0,5.4,"[HU, DE, FR, RO, RU, JP]",3,0,1,[silent],0,4
2,Chinese Opium Den,"(4, 5]",1894,1894.0,1.0,0,195,1,10,1,...,0,1,5.0,"[US, DE, PT, HU, RU]",4,0,1,[silent],0,2
3,Edison Kinetoscopic Record of a Sneeze,"(5, 6]",1894,1894.0,1.0,1,2237,1,10,3,...,1,6,5.4,"[UA, JP, HU, US, DE, RU]",6,0,1,[silent],0,7
4,L'arrivée d'un train à La Ciotat,"(7, 8]",1896,1896.0,1.0,0,13115,1,10,12,...,6,5,7.4,"[HU, DE, TR, FI, FR, IT, ES, SK, PL, GB, XWW, ...",21,0,2,[silent],0,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149526,Nuestra película,"(6, 7]",1993,1993.0,96.0,0,11,1,10,0,...,0,2,7.0,[CO],1,1,1,[],0,11
149527,Eco,"(6, 7]",2019,2019.0,14.0,0,15,1,10,4,...,6,3,6.4,[ES],5,1,1,[],0,57
149528,Women Take Center Stage,"(5, 6]",2019,2019.0,NaN,0,12,1,10,2,...,1,0,5.6,[],0,0,0,[],0,37
149529,Horrid Henry and the Christening Crisis,"(7, 8]",2011,2011.0,10.0,0,9,1,10,1,...,7,0,7.1,[],0,3,1,[],0,16
149530,A lenda do soprador de vidro,"(8, 9]",2019,2019.0,NaN,0,9,1,10,3,...,9,0,8.6,[],0,3,2,[],0,36

In [ ]:
# rows w/out country of origin total vs rows w/out country of origin
# and with only one region
(len(df.loc[df['countryOfOrigin'].apply(lambda x: len(x)) == 0]),
 len(df.loc[(df['countryOfOrigin'].apply(lambda x: len(x)) == 0) &
            (df['regions'].apply(lambda x: len(x)) == 1)]))

(39987, 219)